/*
 * 银龄健康管家 · 演示数据
 * ------------------------------------------------------------
 * 本文件只保存默认的本地演示数据。实际运行中的改变会保存在浏览器 localStorage，
 * 便于在“张阿姨 / 小李”间切换时演示同一家庭数据的变化。
 */

window.SILVER_SEED_DATA = {
  family: {
    id: 'family-silver-2026',
    name: '张阿姨的健康小家',
    inviteCode: 'SILVER2026',
  },
  accounts: [
    {
      id: 'elder-zhang',
      name: '张阿姨',
      role: 'elder',
      age: 68,
      relation: '本人',
      avatar: '张',
      fontMode: 'elder',
      profileId: 'profile-zhang',
    },
    {
      id: 'child-li',
      name: '小李',
      role: 'child',
      age: 37,
      relation: '女儿',
      avatar: '李',
      fontMode: 'normal',
      selectedProfileId: 'profile-zhang',
    },
  ],
  elderProfiles: [
    {
      id: 'profile-zhang',
      name: '张阿姨',
      relation: '母亲',
      age: 68,
      avatar: '张',
      tag: '高血压管理中',
      note: '家人已授权小李协助查看和录入健康记录',
    },
    {
      id: 'profile-wang',
      name: '王叔叔',
      relation: '父亲',
      age: 71,
      avatar: '王',
      tag: '规律随访中',
      note: '家人已授权小李协助查看和录入健康记录',
    },
  ],
  medicationPlans: [
    {
      id: 'med-amlodipine',
      profileId: 'profile-zhang',
      name: '氨氯地平片',
      doseValue: 1,
      doseUnit: '片',
      slots: ['早餐后'],
      startDate: '2026-09-01',
      duration: '长期服用',
      source: '家属协助录入',
      status: 'active',
      color: 'blue',
      note: '请按实际处方服用',
    },
    {
      id: 'med-metformin',
      profileId: 'profile-zhang',
      name: '二甲双胍片',
      doseValue: 1,
      doseUnit: '片',
      slots: ['早餐后', '晚餐后'],
      startDate: '2026-09-01',
      duration: '长期服用',
      source: '手动录入',
      status: 'active',
      color: 'coral',
      note: '请按实际处方服用',
    },
    {
      id: 'med-atorvastatin',
      profileId: 'profile-zhang',
      name: '阿托伐他汀钙片',
      doseValue: 1,
      doseUnit: '片',
      slots: ['睡前'],
      startDate: '2026-09-01',
      duration: '长期服用',
      source: '模拟拍照识别',
      status: 'active',
      color: 'purple',
      note: '请按实际处方服用',
    },
    {
      id: 'med-aspirin',
      profileId: 'profile-wang',
      name: '阿司匹林肠溶片',
      doseValue: 1,
      doseUnit: '片',
      slots: ['早餐后'],
      startDate: '2026-09-02',
      duration: '长期服用',
      source: '手动录入',
      status: 'active',
      color: 'amber',
      note: '请按实际处方服用',
    },
    {
      id: 'med-irbesartan',
      profileId: 'profile-wang',
      name: '厄贝沙坦片',
      doseValue: 1,
      doseUnit: '片',
      slots: ['晚餐后'],
      startDate: '2026-09-02',
      duration: '长期服用',
      source: '家属协助录入',
      status: 'active',
      color: 'blue',
      note: '请按实际处方服用',
    },
  ],
  /*
   * 初始打卡事件全部对应“2026-09-13”演示日。
   * app.js 会把展示的“今天”固定为同一天，以确保比赛现场无论何时打开，
   * 都能稳定看见早餐已完成、晚餐逾期提醒、睡前待办这三个状态。
   */
  doseEvents: [
    {
      id: 'event-amlodipine-breakfast',
      profileId: 'profile-zhang',
      planId: 'med-amlodipine',
      slot: '早餐后',
      scheduledTime: '08:00',
      date: '2026-09-13',
      status: 'taken_on_time',
      recordedAt: '08:12',
      recordedBy: 'elder-zhang',
    },
    {
      id: 'event-metformin-breakfast',
      profileId: 'profile-zhang',
      planId: 'med-metformin',
      slot: '早餐后',
      scheduledTime: '08:00',
      date: '2026-09-13',
      status: 'taken_on_time',
      recordedAt: '08:13',
      recordedBy: 'elder-zhang',
    },
    {
      id: 'event-metformin-dinner',
      profileId: 'profile-zhang',
      planId: 'med-metformin',
      slot: '晚餐后',
      scheduledTime: '18:30',
      date: '2026-09-13',
      status: 'overdue',
      recordedAt: null,
      recordedBy: null,
    },
    {
      id: 'event-atorvastatin-bedtime',
      profileId: 'profile-zhang',
      planId: 'med-atorvastatin',
      slot: '睡前',
      scheduledTime: '21:00',
      date: '2026-09-13',
      status: 'pending',
      recordedAt: null,
      recordedBy: null,
    },
    {
      id: 'event-aspirin-breakfast',
      profileId: 'profile-wang',
      planId: 'med-aspirin',
      slot: '早餐后',
      scheduledTime: '08:00',
      date: '2026-09-13',
      status: 'taken_on_time',
      recordedAt: '08:05',
      recordedBy: null,
      recordedByName: '王叔叔（演示记录）',
    },
    {
      id: 'event-irbesartan-dinner',
      profileId: 'profile-wang',
      planId: 'med-irbesartan',
      slot: '晚餐后',
      scheduledTime: '18:30',
      date: '2026-09-13',
      status: 'pending',
      recordedAt: null,
      recordedBy: null,
    },
  ],
  healthRecords: [
    {
      id: 'bp-0909',
      profileId: 'profile-zhang',
      type: 'blood_pressure',
      measuredAt: '2026-09-09 08:05',
      source: '手动录入',
      values: { systolic: 136, diastolic: 85, pulse: 72 },
      note: '晨起后测量',
    },
    {
      id: 'bp-0910',
      profileId: 'profile-zhang',
      type: 'blood_pressure',
      measuredAt: '2026-09-10 08:10',
      source: '模拟设备导入',
      values: { systolic: 134, diastolic: 84, pulse: 70 },
      note: '来自模拟血压计',
    },
    {
      id: 'bp-0911',
      profileId: 'profile-zhang',
      type: 'blood_pressure',
      measuredAt: '2026-09-11 08:02',
      source: '手动录入',
      values: { systolic: 132, diastolic: 82, pulse: 72 },
      note: '晨起后测量',
    },
    {
      id: 'bp-0912',
      profileId: 'profile-zhang',
      type: 'blood_pressure',
      measuredAt: '2026-09-12 08:07',
      source: '模拟设备导入',
      values: { systolic: 130, diastolic: 80, pulse: 69 },
      note: '来自模拟华为健康',
    },
    {
      id: 'lipid-0901',
      profileId: 'profile-zhang',
      type: 'blood_lipid',
      measuredAt: '2026-09-01 09:30',
      source: '手动录入',
      values: { tc: 4.2, tg: 1.1, hdl: 1.3, ldl: 2.1 },
      note: '体检报告原始记录',
    },
    {
      id: 'body-0908',
      profileId: 'profile-zhang',
      type: 'body',
      measuredAt: '2026-09-08 07:30',
      source: '模拟设备导入',
      values: { height: 158, weight: 56.2, fat: 31.4 },
      note: '来自模拟智能体脂秤',
    },
    {
      id: 'bp-wang-0912',
      profileId: 'profile-wang',
      type: 'blood_pressure',
      measuredAt: '2026-09-12 08:20',
      source: '手动录入',
      values: { systolic: 128, diastolic: 78, pulse: 68 },
      note: '晨起后测量',
    },
  ],
  notificationLogs: [
    {
      id: 'notification-1',
      profileId: 'profile-zhang',
      eventId: 'event-metformin-dinner',
      sentAt: '2026-09-13 21:10',
      text: '模拟提醒张阿姨核对晚餐后的用药记录',
    },
  ],
};
