async(page,{artifactDir}={})=>{
 const BASE_URL = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,s)=>{if(!v)throw Error(s);checks.push(s);};await page.goto(`${BASE_URL}/index.html`);
 const data=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1'))),send=async text=>{await page.locator('#chat-input').fill(text);await page.locator('[data-form="chat"] button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('.chat-status').textContent.includes('处理中'));};
 for(const [text,detail,differs]of [['这次已经吃过了，只吃了半粒','半粒',true],['这次已经吃过了，三片','三片',true],['这次已经吃过了，一包','一包',true],['这次吃了三片','三片',true],['这次已经吃过了，实际时间为08:10','08:10',false],['这次药吃过了',null,false],['维生素B12已经吃过了',null,false]]){
  const id=await page.evaluate(()=>{const d=MedRules.prepareSeed(SILVER_SEED_DATA),e=d.doseEvents.find(e=>e.date===MedRules.DAY&&e.slot==='睡前'&&e.profileId==='profile-zhang'),p=d.medicationPlans.find(p=>p.id===e.planId);p.name='维生素B12';e.snapshot.name=p.name;d.medicationPlans=[p];d.doseEvents=[e];d.notificationLogs=[];if(!MedRules.validData(d))throw Error('fixture invalid');localStorage.setItem('silver-health-data-v1',JSON.stringify(d));sessionStorage.clear();return e.id;});await page.reload();if(await page.locator('#modal-root .focus-sheet').count())await page.locator('#modal-root [data-action="close-modal"]').click();await page.locator('[data-action="navigate"][data-page="home"]').click();await page.locator('[data-action="assistant"]').click();await send('今天吃什么药');await page.locator(`#modal-root [data-action="chat-task"][data-id="${id}"]`).click();await send('这次已经吃过了，只吃了半粒吗？');ok((await data()).doseEvents[0].status==='pending'&&(await data()).doseEvents[0].changes.length===0,`疑问句仍不记录（随后测试${text}）`);await send(text);const d=await data(),e=d.doseEvents[0];ok(e.status==='taken'&&(detail?e.actual?.includes(detail):e.actual===null),`本人补充细节正确保留或为空：${text}`);ok(d.doseEvents.length===1&&e.snapshot.doseValue===1&&(!!e.actual?.includes('与计划不同'))===differs,`原计划不变且差异仅作自述：${text}`);await page.reload();ok((await data()).doseEvents[0].actual===e.actual,`刷新保留本人细节：${text}`);
 }
 await page.screenshot({path:`${artifactDir}/details-preserved.png`,animations:'disabled'});ok(errors.length===0,'细节保留检查无脚本错误');return{passed:checks.length,checks,errors};
}
