async(page,{artifactDir='output/playwright/step-04'}={})=>{
  const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  const ok=(v,label)=>{if(!v)throw Error(`${label}；最后通过：${checks.at(-1)}`);checks.push(label);};
  const click=a=>page.locator(`[data-action="${a}"]:visible`).first().click();
  const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')));
  const nav=p=>page.locator(`[data-action="navigate"][data-page="${p}"]`).click();
  const closeFocus=async()=>{if(await page.locator('#modal-root .focus-sheet').count()){await page.locator('#modal-root [data-action="close-modal"]').click();await nav('home');}};
  const send=async text=>{await page.locator('#chat-input').fill(text);await page.locator('[data-form="chat"] button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('.chat-status')?.textContent.includes('处理中'));};
  const transcript=()=>page.locator('.chat-stream').innerText();
  await page.goto('http://127.0.0.1:8765/index.html');await page.evaluate(()=>{localStorage.clear();sessionStorage.clear();});await page.reload();await closeFocus();
  await nav('me');await click('clock');await page.locator('[name="time"]').fill('06:00');await page.locator('[data-form="clock"] button[type="submit"]').click();await nav('home');
  await click('assistant');ok((await transcript()).includes('张阿姨，您好')&&await page.locator('#chat-input').isVisible(),'首页点击助手主动问候文字输入');ok(!(await page.locator('body').innerText()).includes('正在聆听'),'不冒充真实麦克风');
  const initial=await state();await send('那个，示例药，每次一片，早晚吃');ok(await page.locator('[name="name"]').inputValue()==='示例药'&&await page.locator('[name="doseValue"]').inputValue()==='1','实际文字提取药名与每次用量');ok(await page.locator('[name="slots"]:checked').count()===0&&await page.locator('[data-action="chat-confirm-slots"]').count()===1,'早晚保留待确认且不猜餐时');
  ok((await state()).medicationPlans.length===initial.medicationPlans.length,'未确认草稿不落库');await click('chat-confirm-slots');await send('不是一片，是半片');ok(await page.locator('[name="doseValue"]').inputValue()==='0.5','明确否定改口只改计划量');
  await click('chat-form-plan');await page.locator('[data-slot="早餐"][data-meal="餐前"]').click();await page.locator('[name="name"]').fill('用户改名示例药');await page.locator('[data-action="med-mode"][data-value="voice"]').click();
  ok(await page.locator('[name="name"]').inputValue()==='用户改名示例药'&&await page.locator('[data-slot="早餐"][data-meal="餐前"]').getAttribute('aria-pressed')==='true','手动返回聊天不覆盖药名餐时');await send('早餐饭前改饭后');ok(await page.locator('[data-slot="早餐"][data-meal="餐后"]').getAttribute('aria-pressed')==='true','新输入仅更改指定餐时');
  await page.locator('[data-form="chat-plan"] button[type="submit"]').click();ok((await page.getByRole('dialog').innerText()).includes('0.5 片')&&(await page.getByRole('dialog').innerText()).includes('文字输入'),'共用核对包含剂量与真实来源');await page.locator('[data-action="save-med"]').evaluate(e=>{e.click();e.click();});
  const saved=await state(),plan=saved.medicationPlans.find(p=>p.name==='用户改名示例药');ok(plan&&saved.medicationPlans.filter(p=>p.name===plan.name).length===1,'重复确认只创建一份计划');ok(plan.source.includes('文字输入')&&plan.source.includes('手动修改'),'文字与手动混合来源存档');ok(saved.doseEvents.filter(e=>e.planId===plan.id).every(e=>e.status==='pending'),'建计划不生成服药事实');
  await send('今天晚上吃什么');ok((await page.locator('.chat-tasks').innerText()).includes('用户改名示例药')&&!(await page.locator('.chat-tasks').innerText()).includes('早餐'),'晚间查询读取新增计划和晚餐睡前范围');await page.locator('[data-action="chat-task"]').filter({hasText:'选择'}).last().click();await send('几点提醒，吃多少');ok((await transcript()).includes('按已保存的计划'),'选中任务后查询不进入建计划');
  await page.locator('[data-action="chat-intent"][data-intent="plan"]').click();await send('药名是第二种药，每次2包，早餐，长期服用');await page.locator('[data-action="chat-mode"][data-mode="voice"]').click();await page.locator('[data-chat-example]').selectOption('3');await click('voice-experience');ok(await page.locator('#chat-input').inputValue()==='不是一片，是半片'&&await page.locator('[name="doseValue"]').inputValue()==='2','示例预览未发送不改草稿');await click('voice-cancel');ok(await page.locator('[name="doseValue"]').inputValue()==='2','取消示例不改变候选或存档');await page.locator('[data-chat-example]').selectOption('3');await click('voice-experience');await send('不是2包，是0.75包');ok(await page.locator('[name="doseValue"]').inputValue()==='0.75','编辑示例结果随输入变化');
  await page.locator('[data-form="chat-plan"] button[type="submit"]').click();await click('save-med');ok((await state()).medicationPlans.find(p=>p.name==='第二种药').source.includes('示例输入（模拟）'),'示例来源保留至确认存档');
  await send('高压125，低压75，今天05:30测量，医生说遵照原安排');await click('chat-form-health');ok(await page.locator('[name="systolic"]').inputValue()==='125'&&await page.locator('[name="diastolic"]').inputValue()==='75','血压口语映射规范字段');await page.locator('[data-form="health"] button[type="submit"]').click();await click('save-health');ok((await state()).healthRecords.at(-1).note.includes('用户转述')&&(await state()).healthRecords.at(-1).source.includes('文字输入'),'测量确认保存带来源与转述标记');
  await send('身高160厘米，体重60公斤，今天05:30测量');await click('chat-form-health');await page.locator('[data-form="health"] button[type="submit"]').click();ok(await page.getByText('23.4',{exact:true}).count()===1,'聊天身体数据共用BMI核对');await click('save-health');
  await send('总胆固醇120 mg/dL，甘油三酯1.2 mmol/L，今天05:30测量');await click('chat-form-health');await page.locator('[data-form="health"] button[type="submit"]').click();ok(await page.locator('[data-form="health"]').count()===1&&(await page.locator('#form-error').innerText()).includes('单位无法确认'),'未知单位阻止整份测量核对');await click('close-modal');await send('甘油三酯1.3 mmol/L');await click('chat-form-health');await page.locator('[data-form="health"] button[type="submit"]').click();ok((await page.locator('#form-error').innerText()).includes('单位无法确认'),'补另一指标不会清除原指标单位冲突');await click('close-modal');
  await send('总胆固醇4.8 mmol/L，甘油三酯1.2 mmol/L，今天05:30测量');await click('chat-form-health');await page.locator('[data-form="health"] button[type="submit"]').click();await click('save-health');const lipid=(await state()).healthRecords.at(-1);ok(lipid.type==='blood_lipid'&&lipid.values.tc===4.8&&lipid.values.hdl===undefined,'血脂只保存明确提供项目');await send('查询午餐用药安排');ok((await transcript()).includes('当前没有找到对应的用药计划／任务')&&await page.locator('.chat-tasks .chat-task').count()===0,'空时段查询如实返回无任务');const beforeMedical=JSON.stringify(await state());await send('应该加量吗');ok((await transcript()).includes('不能推荐药物、增减剂量')&&JSON.stringify(await state())===beforeMedical,'医疗决定问题不产生建议或业务修改');
  await page.locator('#modal-root [data-action="close-modal"]').click();await page.reload();ok((await state()).medicationPlans.some(p=>p.name==='第二种药')&&(await state()).healthRecords.some(r=>r.type==='body'&&r.values.height===160),'确认结果刷新后保留');await closeFocus();await nav('home');
  await click('home-add-med');await page.locator('[name="name"]').fill('手动入口保留药');await page.locator('[data-action="med-mode"][data-value="voice"]').click();ok((await transcript()).includes('我来帮您整理用药计划')&&await page.locator('[name="name"]').inputValue()==='手动入口保留药','加药入口直接收集且保留手动字段');ok(!(await transcript()).includes('您想做什么'),'加药不重复询问意图');
  for(const width of [360,1280])for(const font of ['normal','elder']){await click('close-modal');await nav('me');await page.locator(`[data-action="font"][data-value="${font}"]`).click();await nav('home');await page.setViewportSize({width,height:850});await click('assistant');await page.locator('#modal-root .slot-grid').scrollIntoViewIfNeeded();ok(await page.locator('#modal-root .slot-grid').evaluate(e=>e.scrollWidth<=e.clientWidth+1),`聊天四列配置卡无溢出${width}/${font}`);await page.screenshot({path:`${artifactDir}/chat-plan-${width}-${font}.png`,animations:'disabled'});ok(await page.locator('#chat-input').isVisible(),`配置卡滚动时输入栏可见${width}/${font}`);}
  ok(errors.length===0,`脚本错误${errors.length}`);return{passed:checks.length,checks,errors};
}
