async(page,{artifactDir,theme='ios'}={})=>{
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,s)=>{if(!v)throw Error(`${theme} ${s}；最后通过${checks.at(-1)}`);checks.push(`${theme}：${s}`);};await page.goto('http://127.0.0.1:8765/demo.html');await page.waitForFunction(()=>document.querySelector('#ready-status').textContent.includes('已就绪'));const f=page.frames().find(f=>f.url().includes('index.html?demo=1'));
 const control=async(type,payload={})=>page.evaluate(({type,payload})=>new Promise((resolve,reject)=>{const frame=document.getElementById('app-frame'),requestId=`layout-${Math.random()}`,timer=setTimeout(()=>{removeEventListener('message',handle);reject(Error('ACK timeout'));},5000);function handle(e){if(e.source===frame.contentWindow&&e.data?.type==='ACK'&&e.data.requestId===requestId){clearTimeout(timer);removeEventListener('message',handle);resolve(e.data.payload);}}addEventListener('message',handle);frame.contentWindow.postMessage({channel:'yaoanxin-demo',version:1,requestId,type,payload},location.origin);}),{type,payload});
 const click=a=>f.locator(`#modal-root [data-action="${a}"]:visible`).first().click(),nav=p=>f.locator(`[data-action="navigate"][data-page="${p}"]`).click();const setTheme=async()=>{await page.locator(`.system-picker [data-os="${theme}"]`).click();await page.waitForFunction(os=>document.querySelector('#phone').dataset.os===os&&document.querySelector('#app-container').style.visibility==='visible',theme);await f.waitForFunction(os=>document.documentElement.dataset.os===os,theme);};
 const show=async()=>{await page.locator('#open-app').click();await f.waitForFunction(()=>!document.getElementById('app').inert);};const closeFocus=async()=>{if(await f.locator('#modal-root .focus-sheet').count()){await click('close-modal');await nav('home');}};
 const shot=async(label,width,font)=>{ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)&&await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${label}页面无横溢${width}/${font}`);await page.screenshot({path:`${artifactDir}/${theme}-${label}-${width}-${font}.png`,animations:'disabled'});};
 for(const width of [360,1280])for(const font of ['normal','elder']){
  await page.setViewportSize({width,height:1000});await show();await control('RESET_REQUEST');await click('confirm-reset');await closeFocus();await control('CLOCK',{dateOffset:0,time:'06:00'});await setTheme();await nav('me');await f.locator(`[data-action="font"][data-value="${font}"]`).click();await nav('home');await shot('elder',width,font);ok(await f.locator('[data-action="assistant"]').evaluate(e=>{const a=e.getBoundingClientRect(),b=document.querySelector('.bottom-nav').getBoundingClientRect();return a.bottom<=b.top+1;}),`助手入口不挡导航${width}/${font}`);
  await control('SWITCH_ACCOUNT',{accountId:'child-li'});await nav('me');await f.locator(`[data-action="font"][data-value="${font}"]`).click();await nav('home');await shot('dashboard',width,font);await f.locator('[data-action="home-add-med"]').click();await f.locator('[name="name"]').fill('布局核对药');await f.locator('[name="doseValue"]').fill('0.5');await f.locator('[name="doseUnit"]').fill('小包');await f.locator('[name="slots"][value="早餐"]').check();await f.locator('[name="slots"][value="晚餐"]').check();await f.locator('#modal-root .slot-grid').scrollIntoViewIfNeeded();ok(await f.locator('#modal-root .slot-grid').evaluate(e=>e.scrollWidth<=e.clientWidth+1),`四列表内部无裁切${width}/${font}`);await shot('form',width,font);
  await f.locator('[data-action="time-picker"][data-slot="早餐"][data-part="minute"]').click();ok(await f.locator('.wheel-list').count()===2,`小时分钟两个滚轮${width}/${font}`);await shot('wheel',width,font);await f.locator('[name="minute"]').focus();await page.keyboard.press('Escape');ok(await f.locator('.wheel-list').count()===0&&await f.locator('[data-form="medicine"]').count()===1,`键盘关闭滚轮回原表单${width}/${font}`);await f.locator('[data-form="medicine"] button[type="submit"]').click();await shot('review',width,font);ok((await f.getByRole('dialog').innerText()).includes('0.5 小包'),`核对内容仍清楚${width}/${font}`);await click('close-modal');
  await nav('plans');await f.locator('[data-action="plan-tab"][data-value="history"]').click();await shot('history',width,font);await nav('health');await shot('health',width,font);
  await control('SWITCH_ACCOUNT',{accountId:'elder-zhang'});await nav('home');await f.locator('[data-action="assistant"]').click();await f.locator('#chat-input').fill('药名是聊天布局药，每次1片，早餐和晚餐');await f.locator('[data-form="chat"] button[type="submit"]').click();await f.waitForFunction(()=>!document.querySelector('.chat-status').textContent.includes('处理中'));await f.locator('[data-action="chat-mode"][data-mode="voice"]').click();await f.locator('#modal-root .slot-grid').scrollIntoViewIfNeeded();ok(await f.locator('#modal-root .slot-grid').evaluate(e=>e.scrollWidth<=e.clientWidth+1),`聊天四列内部无裁切${width}/${font}`);ok(await f.locator('#chat-input').evaluate(e=>{const r=e.getBoundingClientRect();return r.top>=0&&r.bottom<=innerHeight;}),`模拟语音加配置卡的输入栏可见${width}/${font}`);await shot('chat',width,font);
  await f.locator('#chat-input').focus();await page.keyboard.press('Tab');ok(await f.evaluate(()=>document.getElementById('modal-root').contains(document.activeElement)),`聊天键盘焦点留在当前弹窗${width}/${font}`);await click('close-modal');await control('CLOCK',{dateOffset:0,time:'21:15'});await page.locator('#show-desktop').click();await f.waitForFunction(()=>document.getElementById('app').inert);await show();await f.locator('#modal-root .focus-sheet').waitFor();await shot('focus',width,font);ok(await f.locator('#modal-root [data-action="take"]').evaluate(e=>e.getBoundingClientRect().height>=44),`聚焦本人按钮足够大${width}/${font}`);await click('close-modal');
  await page.locator('#show-desktop').click();await f.waitForFunction(()=>document.getElementById('app').inert);await control('SCENE',{kind:'N1'});await shot('desktop',width,font);ok(await page.locator('#launch-app').evaluate(e=>{const r=e.getBoundingClientRect(),s=document.getElementById('screen').getBoundingClientRect();return r.top>=s.top&&r.bottom<=s.bottom;}),`桌面图标位于手机范围${width}/${font}`);if(width===1280&&font==='normal'){await page.locator('#banner-close').click();await shot('desktop-clear',width,font);}
 }
 const before=await f.evaluate(()=>({t:performance.timeOrigin,d:localStorage.getItem('silver-health-data-v1')}));await page.evaluate(()=>{document.querySelector('.system-picker [data-os="ios"]').click();document.querySelector('.system-picker [data-os="android"]').click();document.querySelector('.system-picker [data-os="harmonyos"]').click();});await page.waitForFunction(()=>document.querySelector('#phone').dataset.os==='harmonyos'&&document.querySelector('#app-container').style.visibility==='visible');await f.waitForFunction(()=>document.documentElement.dataset.os==='harmonyos');ok(await f.evaluate(()=>performance.timeOrigin)===before.t,'快速连续主题切换只呈现最后确认主题，不重载');await setTheme();
 await page.locator('#banner-close').click();await show();await closeFocus();await nav('home');const cdp=await page.context().newCDPSession(page);await cdp.send('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-transparency',value:'reduce'},{name:'prefers-reduced-motion',value:'reduce'}]});ok(await page.evaluate(()=>matchMedia('(prefers-reduced-transparency: reduce)').matches&&matchMedia('(prefers-reduced-motion: reduce)').matches),'减少动态和透明媒体条件已实际生效');await page.locator('#show-desktop').click();await show();ok(await page.locator('#app-container').evaluate(e=>getComputedStyle(e).transform==='none'),'减少动态效果时不缩放展开');ok(await page.locator('#banner').evaluate(e=>getComputedStyle(e).backdropFilter==='none'),'减少透明效果时通知为实色');await closeFocus();await f.locator('[data-action="assistant"]').click();ok(await f.locator('.modal-header').evaluate(e=>getComputedStyle(e).backdropFilter==='none'),'减少透明效果时应用弹窗清楚');
 const ax=await cdp.send('Accessibility.getFullAXTree');ok(ax.nodes.some(n=>n.role?.value==='Iframe'&&n.name?.value==='药安心应用')&&ax.nodes.some(n=>n.role?.value==='button'&&n.name?.value==='打开应用'),'辅助功能树包含已命名iframe及外层操作');ok(await f.getByRole('textbox',{name:'输入消息',exact:true}).count()===1&&await f.getByRole('log',{name:'对话消息',exact:true}).count()===1,'聊天输入和动态消息具备可访问名称与角色');await page.screenshot({path:`${artifactDir}/${theme}-reduced-effects.png`,animations:'disabled'});await cdp.detach();ok(errors.length===0,'脚本无错误');return{passed:checks.length,checks,errors,theme};
}
