async(page,{artifactDir='output/playwright/step-04'}={})=>{
  const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,label)=>{if(!v)throw Error(`${label}；最后通过${checks.at(-1)}`);checks.push(label);};
  await page.goto('http://127.0.0.1:8765/demo.html');await page.waitForFunction(()=>document.querySelector('#ready-status').textContent.includes('已就绪'));const f=page.frames().find(f=>f.url().includes('index.html?demo=1'));
  const request=async(type,payload={})=>page.evaluate(({type,payload})=>new Promise(resolve=>{const frame=document.getElementById('app-frame'),requestId=`chat-test-${Math.random()}`;const handler=e=>{if(e.source===frame.contentWindow&&e.data?.type==='ACK'&&e.data.requestId===requestId){removeEventListener('message',handler);resolve(e.data.payload);}};addEventListener('message',handler);frame.contentWindow.postMessage({channel:'yaoanxin-demo',version:1,type,payload,requestId},location.origin);}),{type,payload});
  const click=a=>f.locator(`#modal-root [data-action="${a}"]:visible`).first().click();
  const nav=p=>f.locator(`[data-action="navigate"][data-page="${p}"]`).click();const state=()=>f.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')));
  const transcript=()=>f.locator('.chat-stream').innerText();const send=async text=>{await f.locator('#chat-input').fill(text);await f.locator('[data-form="chat"] button[type="submit"]').click();await f.waitForFunction(()=>!document.querySelector('.chat-status')?.textContent.includes('处理中'));};
  const closeFocus=async()=>{if(await f.locator('#modal-root .focus-sheet').count()){await click('close-modal');await nav('home');}};
  const open=async()=>{await page.locator('#open-app').click();await f.waitForFunction(()=>!document.getElementById('app').inert);};
  await open();await request('RESET_REQUEST');await click('confirm-reset');await closeFocus();
  const entrance=f.locator('[data-action="assistant"]');await entrance.scrollIntoViewIfNeeded();const box=await entrance.boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.waitForTimeout(550);await page.mouse.up();
  ok(await f.getByRole('heading',{name:'AI 助手',exact:true}).count()===1&&await f.locator('[data-chat-example]').count()===1,'长按同一聊天页进入模拟语音一次');ok((await transcript()).match(/张阿姨，您好/g).length===1,'松手不重复欢迎或导航');await click('voice-experience');ok((await transcript()).includes('请先选择示例')&&await f.locator('#chat-input').inputValue()==='','未选示例不生成假识别文字');await f.locator('[data-action="chat-mode"][data-mode="text"]').click();
  const original=await state();await send('这次吃过了');ok((await state()).doseEvents.map(e=>e.status).join()===original.doseEvents.map(e=>e.status).join()&&await f.locator('.chat-tasks .chat-task').count()>1,'多任务指代仅澄清不批量打卡');
  await f.locator('[data-action="chat-task"][data-id="event-atorvastatin-bedtime"]').click();await send('陌生药已经吃过了');ok((await transcript()).includes('还没有找到您提到的对应任务')&&(await state()).doseEvents.find(e=>e.id==='event-atorvastatin-bedtime').status==='pending','未知新药名不沿用上次选中任务');await f.locator('[data-action="chat-intent"][data-intent="query"]').click();await f.locator('[data-action="chat-task"][data-id="event-atorvastatin-bedtime"]').click();await send('没有按时服用');ok((await transcript()).includes('到现在还没有服用，还是后来已经服用了')&&(await state()).doseEvents.find(e=>e.id==='event-atorvastatin-bedtime').status==='pending','含糊否定不提交服药事实');await send('这次已经吃过了，只吃了半片');
  let d=await state(),event=d.doseEvents.find(e=>e.id==='event-atorvastatin-bedtime');ok(event.status==='taken'&&event.actual.includes('与计划不同')&&d.doseEvents.length===original.doseEvents.length,'自述差异只附注，不生成剩余剂量任务');ok((await transcript()).includes('你有未打卡的记录')&&(await f.locator('.chat-selected').innerText()).includes('二甲双胍'),'新记录后只提示合格逾期原任务');
  await f.locator('[data-action="undo"]').click();ok((await state()).doseEvents.find(e=>e.id===event.id).status==='pending','助手声明同样可撤销');await send('还没吃');ok((await state()).doseEvents.find(e=>e.id==='event-metformin-dinner').status==='not_taken','明确还没吃保留否定');
  await f.locator('[data-action="chat-intent"][data-intent="query"]').click();await f.locator('[data-action="chat-task"][data-id="event-metformin-dinner"]').click();await click('correct-dose');await f.locator('[data-action="choose-correction"][data-status="taken"]').click();await click('confirm-dose');ok((await state()).doseEvents.find(e=>e.id==='event-metformin-dinner').changes.length===2,'助手进入本人更正且保留原声明');
  await f.locator('[data-action="chat-intent"][data-intent="query"]').click();await f.locator('[data-action="chat-task"][data-id="event-atorvastatin-bedtime"]').click();await send('延后10分钟');ok((await transcript()).includes('仅支持5分钟或30分钟')&&(await state()).doseEvents.find(e=>e.id===event.id).snoozeUsed===0,'不支持延后值不取近似');ok((await f.locator('.chat-selected').innerText()).includes('21:45'),'延后前展示完整目标时间');await f.locator('#modal-root [data-action="snooze"][data-minutes="30"]').click();ok((await state()).doseEvents.find(e=>e.id===event.id).snoozeUsed===1&&(await state()).doseEvents.find(e=>e.id===event.id).status==='pending','聊天延后只改变提醒');
  await request('SWITCH_ACCOUNT',{accountId:'child-li'});await f.locator('[data-action="assistant"]').click();ok((await transcript()).includes('小李，您好')&&!(await transcript()).includes('只吃了半片'),'子女欢迎和消息隔离');
  await send('今天吃什么药');await f.locator('[data-action="chat-task"][data-id="event-atorvastatin-bedtime"]').click();ok(await f.locator('#modal-root [data-action="take"],#modal-root [data-action="snooze"],#modal-root [data-action="correct-dose"]').count()===0,'子女任务卡无代打更正延后');
  const facts=JSON.stringify((await state()).doseEvents);for(const text of ['这次吃过了','还没吃','补记用药','更正记录','延后5分钟'])await send(text);ok(JSON.stringify((await state()).doseEvents)===facts&&(await transcript()).includes('只有长辈本人'),'子女所有直接文本操作拒绝');await f.locator('[data-action="chat-mode"][data-mode="voice"]').click();await f.locator('[data-chat-example]').selectOption('5');await click('voice-experience');await send('这次已经吃过了');ok(JSON.stringify((await state()).doseEvents)===facts,'子女示例语音同样拒绝代打');
  await send('药名是冲突药，早一片晚两片');ok((await transcript()).includes('各时段相同用量'),'分时不同剂量说明模型限制');await click('chat-form-plan');await f.locator('[name="doseValue"]').fill('1');await f.locator('[name="doseUnit"]').fill('片');await f.locator('[name="name"]').fill('冲突药');await f.locator('[name="slots"][value="早餐"]').check();await f.locator('[data-form="medicine"] button[type="submit"]').click();ok(await f.getByRole('alertdialog').count()===1,'打开手动页或填默认字段不能清除不支持方案');await click('dismiss-errors');await f.locator('[data-action="med-mode"][data-value="voice"]').click();await send('药名是冲突药，改为每天，每次1片，早餐和晚餐');
  await send('每天三次');await f.locator('[data-form="chat-plan"] button[type="submit"]').click();ok(await f.getByRole('alertdialog').count()===1,'次数与所选时段冲突阻止核对');await click('dismiss-errors');await send('每天两次');
  await f.locator('#chat-input').fill('这段尚未发送的原文');const beforeText=await transcript();await page.locator('#show-desktop').click();await request('THEME',{os:'ios'});await open();ok(await f.locator('#chat-input').inputValue()==='这段尚未发送的原文'&&(await transcript())===beforeText,'桌面与主题握手保留消息未发送文字');
  await request('SWITCH_PROFILE',{profileId:'profile-wang'});await f.locator('[data-action="assistant"]').click();ok(!(await transcript()).includes('冲突药'),'切档案不显示旧消息');await send('药名是王叔叔专属草稿，每次2包，早餐');await request('SWITCH_PROFILE',{profileId:'profile-zhang'});ok(await f.locator('#chat-input').inputValue()==='这段尚未发送的原文'&&await f.locator('[name="name"]').inputValue()==='冲突药','回原档案完整恢复聊天与计划');
  await f.locator('#chat-input').fill('今天吃什么药');await f.locator('[data-form="chat"] button[type="submit"]').evaluate(e=>e.click());await request('SWITCH_ACCOUNT',{accountId:'elder-zhang'});await page.waitForTimeout(180);await request('SWITCH_ACCOUNT',{accountId:'child-li'});ok((await transcript()).includes('处理期间切换了对象或页面，本轮未提交'),'异步处理中换账号取消操作保留原文');
  await request('CLOCK',{dateOffset:1,time:'11:00'});const notice=(await state()).notificationLogs.find(n=>n.kind==='N2'&&n.recipientId==='child-li'&&n.date==='2026-09-14');await f.locator('#chat-input').fill('通知打断前的文字');await request('OPEN_NOTIFICATION',{notificationId:notice.id,eventId:notice.eventId,profileId:notice.profileId,date:notice.date,recipientId:notice.recipientId});await f.locator('[data-action="resume-draft"]').click();ok(await f.locator('#chat-input').inputValue()==='通知打断前的文字'&&(await transcript()).includes('冲突药'),'通知打断后恢复原聊天输入');
  await send('今天吃什么药');ok((await f.locator('.chat-tasks').innerText()).includes('2026-09-14'),'时钟变更后查询使用新日期');await f.locator('[data-action="chat-task"]').first().click();const beforeN3=(await state()).notificationLogs.filter(n=>n.kind==='N3').length;await click('remind');ok((await state()).notificationLogs.filter(n=>n.kind==='N3').length===beforeN3+1,'子女聊天对合格任务生成模拟提醒');ok(await f.locator('#modal-root [data-action="remind"]').isDisabled(),'聊天提醒同样受共享冷却约束');
  await f.locator('[data-action="chat-intent"][data-intent="plan"]').click();await f.locator('[data-form="chat-plan"] button[type="submit"]').click();await click('save-med');const assisted=(await state()).medicationPlans.find(p=>p.name==='冲突药');ok(assisted?.createdBy==='child-li'&&assisted.assisted&&assisted.profileId==='profile-zhang','子女聊天确认创建绑定对象计划并标家属协助');await send('今天吃什么药');
  for(const width of [360,1280])for(const font of ['normal','elder']){
    await page.setViewportSize({width,height:950});await click('close-modal');await nav('me');await f.locator(`[data-action="font"][data-value="${font}"]`).click();await nav('home');await f.locator('[data-action="assistant"]').click();await f.locator('[data-action="chat-mode"][data-mode="text"]').click();
    ok(await f.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)&&await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`内外聊天无横向溢出${width}/${font}`);ok(await f.locator('[data-form="chat"] button[type="submit"]').isVisible(),`输入发送按钮可见${width}/${font}`);await page.screenshot({path:`${artifactDir}/chat-${width}-${font}.png`,animations:'disabled'});
  }
  await request('RESET_REQUEST');await click('confirm-reset');await closeFocus();await f.locator('[data-action="assistant"]').click();ok(!(await transcript()).includes('冲突药')&&await f.locator('#chat-input').inputValue()==='','恢复数据清空所有聊天和未发送草稿');
  ok(errors.length===0,`脚本错误${errors.length}`);return{passed:checks.length,checks,errors};
}
