async(page,{artifactDir}={})=>{
 const BASE_URL = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,s)=>{if(!v)throw Error(`${s}；最后通过 ${checks.at(-1)}`);checks.push(s);};let f=page;const click=async a=>{const inside=f.locator(`#modal-root [data-action="${a}"]:visible`);return(await inside.count()?inside:f.locator(`[data-action="${a}"]:visible`)).first().click();},nav=p=>f.locator(`[data-action="navigate"][data-page="${p}"]`).click();const closeFocus=async()=>{if(await f.locator('#modal-root .focus-sheet').count()){await click('close-modal');await nav('home');}};
 await page.goto(`${BASE_URL}/index.html`);await page.evaluate(()=>{localStorage.setItem('silver-health-data-v1','{bad-archive');sessionStorage.clear();});await page.reload();ok(await page.locator('.storage-warning').count()===1,'无效JSON存档显示降级说明');await click('take');ok(await page.evaluate(()=>localStorage.getItem('silver-health-data-v1'))==='{bad-archive','降级操作不覆盖原损坏存档');
 await page.evaluate(()=>{const d=structuredClone(SILVER_SEED_DATA);d.version=1;localStorage.setItem('silver-health-data-v1',JSON.stringify(d));sessionStorage.clear();});await page.reload();await closeFocus();ok(await page.getByText(/旧版来源保留/).count()>0,'真实v1旧存档通过load迁移并显示来源');const migrated=await page.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')));ok(migrated.version===2&&migrated.doseEvents[0].legacy.status==='taken_on_time','迁移保存v2但保留旧枚举来源');await page.reload();ok(await page.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')).version)===2,'迁移后刷新稳定');
 const malformed=await page.evaluate(()=>{const d=structuredClone(SILVER_SEED_DATA);d.accounts=[null];const raw=JSON.stringify(d);localStorage.setItem('silver-health-data-v1',raw);sessionStorage.clear();return raw;});await page.reload();await click('take');ok(await page.evaluate(()=>localStorage.getItem('silver-health-data-v1'))===malformed,'迁移TypeError同样保留原存档不覆盖');await closeFocus();await nav('me');await click('reset');await click('confirm-reset');await closeFocus();let d=await page.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')));ok(d.version===2&&d.dateOffset===0&&d.notificationStyle==='ios'&&d.doseEvents.every(e=>!e.snoozeUsed),'完整重置清掉无效隔离并恢复规则默认值');
 await page.evaluate(()=>{const d=MedRules.prepareSeed(SILVER_SEED_DATA);d.medicationPlans=[];d.doseEvents=[];d.healthRecords=[];d.notificationLogs=[];localStorage.setItem('silver-health-data-v1',JSON.stringify(d));sessionStorage.clear();});await page.reload();ok(await page.getByRole('heading',{name:'今天已记录 0/0',exact:true}).count()===1,'无任务首页显示0/0且不造任务');await click('assistant');await page.locator('#chat-input').fill('今天吃什么药');await page.locator('[data-form="chat"] button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('.chat-status').textContent.includes('处理中'));ok((await page.locator('.chat-stream').innerText()).includes('当前没有找到')&&await page.locator('.chat-task').count()===0,'空任务聊天如实回答无安排');await click('close-modal');await nav('me');await page.locator('[data-action="switch-account"][data-id="child-li"]').click();await nav('home');ok(await page.locator('.health-summary').getByText('暂无记录',{exact:true}).count()===3&&await page.locator('.calendar-date .icon-star').count()===0,'三类测量空值不填零且无任务日无星');
 await page.locator('[data-action="home-add-med"]').click();const name='<img src=x onerror=window.__xss=1>';await page.locator('[name="name"]').fill(name);await page.locator('[name="doseValue"]').fill('1');await page.locator('[name="doseUnit"]').fill('<u>&"');await page.locator('[name="slots"][value="早餐"]').check();await page.locator('[name="startDate"]').fill('2026-09-14');await page.locator('[data-form="medicine"] button[type="submit"]').click();ok((await page.getByRole('dialog').innerText()).includes(name)&&await page.locator('#modal-root img').count()===0,'核对页药名和自定义单位按文字转义');await click('save-med');d=await page.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')));const plan=d.medicationPlans[0];ok(d.doseEvents.length===0&&plan.startDate==='2026-09-14','未来开始计划不追造今天任务');ok(await page.evaluate(()=>window.__xss===undefined),'应用显示用户输入未执行HTML');
 await page.goto(`${BASE_URL}/demo.html`);await page.waitForFunction(()=>document.querySelector('#ready-status').textContent.includes('已就绪'));f=page.frames().find(f=>f.url().includes('index.html?demo=1'));await page.locator('#account-select').selectOption('elder-zhang');await page.locator('#day-offset').fill('1');await page.locator('#clock-time').fill('08:00');await page.locator('#apply-clock').click();await f.waitForFunction(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')).dateOffset===1);await page.locator('#notice-select').selectOption({index:0});await page.locator('#replay-notice').click();ok((await page.locator('#banner-body').innerText()).includes(name)&&await page.locator('#banner img').count()===0&&await page.evaluate(()=>window.__xss===undefined),'外层通知也按纯文字呈现输入不执行HTML');
 await page.locator('#open-app').click();await f.waitForFunction(()=>!document.getElementById('app').inert);await closeFocus();await nav('me');const labels=await f.locator('button,a,input[type="file"]').allTextContents();ok(!labels.some(t=>/充值|会员|PRO|存钱罐|提现|拍照识药|扫码识药|报告导出|换装|气泡/.test(t))&&await f.locator('input[type="file"]').count()===0,'当前交互入口无付费金融OCR报告形象范围回潮');ok((await f.locator('.page-content').innerText()).includes('演示'),'独立应用与舞台均保留演示说明');await page.screenshot({path:`${artifactDir}/scope-and-invalid-data.png`,animations:'disabled'});ok(errors.length===0,'边界数据无脚本错误');return{passed:checks.length,checks,errors};
}
