async(page,{artifactDir='output/playwright/step-04'}={})=>{
 const BASE_URL = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
 const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,s)=>{if(!v)throw Error(s);checks.push(s);};const click=a=>page.locator(`[data-action="${a}"]:visible`).first().click();const nav=p=>page.locator(`[data-action="navigate"][data-page="${p}"]`).click();const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')));const send=async text=>{await page.locator('#chat-input').fill(text);await page.locator('[data-form="chat"] button[type="submit"]').click();await page.waitForFunction(()=>!document.querySelector('.chat-status')?.textContent.includes('处理中'));};
 await page.goto(`${BASE_URL}/index.html`);await click('close-modal');await nav('home');await click('assistant');await send('今天吃什么药');await page.locator('[data-action="chat-task"][data-id="event-atorvastatin-bedtime"]').click();const original=(await state()).doseEvents.find(e=>e.id==='event-atorvastatin-bedtime');
 for(const text of ['这次吃过了吗？','这次还没吃吗？','这次已经吃过了没有','这次已经吃过了吧','如果吃过了','吃过了，但还没吃','不要记录已服用']){await page.locator('[data-action="chat-intent"][data-intent="query"]').click();await page.locator('[data-action="chat-task"][data-id="event-atorvastatin-bedtime"]').click();await send(text);ok(JSON.stringify((await state()).doseEvents.find(e=>e.id===original.id))===JSON.stringify(original),`疑问与非事实保持原任务及审计：${text}`);}
 await send('药名是跨入口草稿药，每次半片，早餐和晚餐，早餐餐前');await send('早餐不要餐前，改为餐后');ok(await page.locator('[name="slots"][value="早餐"]').isChecked()&&await page.locator('[name="slots"][value="晚餐"]').isChecked(),'餐时否定保留两个服用时段');ok(await page.locator('[data-action="meal"][data-slot="早餐"][data-meal="餐后"]').getAttribute('aria-pressed')==='true','只将早餐改为餐后');
 await send('早餐不要餐前');ok(await page.locator('[data-action="meal"][data-slot="早餐"][data-meal="餐后"]').getAttribute('aria-pressed')==='true'&&await page.locator('[name="slots"][value="早餐"]').isChecked()&&await page.locator('[name="slots"][value="晚餐"]').isChecked(),'孤立否定不写回被否定的餐前且保留时段');
 await page.locator('#chat-input').fill('跨入口还没发送的消息');const messages=await page.locator('.chat-stream').innerText();await click('close-modal');await nav('home');await click('home-add-med');ok(await page.locator('[name="name"]').inputValue()==='跨入口草稿药'&&await page.locator('[name="doseValue"]').inputValue()==='0.5','另一入口的手动页连接已有草稿');await page.locator('[data-action="med-mode"][data-value="voice"]').click();ok(await page.locator('[name="name"]').inputValue()==='跨入口草稿药'&&await page.locator('[name="doseValue"]').inputValue()==='0.5'&&await page.locator('[name="slots"][value="晚餐"]').isChecked(),'空入口不能覆盖既有聊天字段');ok((await page.locator('.chat-stream').innerText())===messages&&await page.locator('#chat-input').inputValue()==='跨入口还没发送的消息','跨入口保持消息和未发送原文');
 await click('close-modal');await nav('plans');await page.locator('[data-action="plan-tab"][data-value="active"]').click();const before=await state(),plan=before.medicationPlans[0];await page.locator(`[data-action="plan-detail"][data-id="${plan.id}"]`).click();await click('edit-plan');await page.locator('[data-action="med-mode"][data-value="voice"]').click();await send('每次半片');await page.locator('[data-form="chat-plan"] button[type="submit"]').click();ok((await page.getByRole('dialog').innerText()).includes('编辑仅影响未开始时段'),'助手编辑核对沿用旧计划身份');await click('save-med');const after=await state(),edited=after.medicationPlans.find(p=>p.id===plan.id);ok(after.medicationPlans.length===before.medicationPlans.length&&edited.version===plan.version+1&&edited.doseValue===0.5,'编辑助手保存仅更新原计划与版本');ok(before.doseEvents.filter(e=>e.planId===plan.id&&e.started).every(old=>JSON.stringify(after.doseEvents.find(e=>e.id===old.id)?.snapshot)===JSON.stringify(old.snapshot)),'已开始任务保留原快照');await page.reload();ok((await state()).medicationPlans.find(p=>p.id===plan.id).version===edited.version,'助手编辑刷新后仍为同一计划');
 await page.screenshot({path:`${artifactDir}/audit-after-edit.png`,animations:'disabled'});
 ok(errors.length===0,'脚本无错误');return{passed:checks.length,checks,errors};
}
