async(page,{artifactDir='output/playwright/step-03'}={})=>{
  const BASE_URL = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
  const checks=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
  const ok=(v,label)=>{if(!v)throw Error(`${label}；最后通过${checks.at(-1)}`);checks.push(label);};
  await page.goto(`${BASE_URL}/demo.html`);await page.waitForFunction(()=>document.getElementById('ready-status').textContent.includes('已就绪'));
  let f=page.frames().find(f=>f.url().includes('index.html?demo=1'));
  const state=()=>f.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1')));
  const request=async(type,payload={})=>page.evaluate(({type,payload})=>new Promise(resolve=>{const iframe=document.getElementById('app-frame'),requestId=`extra-${Math.random()}`;const handler=e=>{if(e.source===iframe.contentWindow&&e.data?.type==='ACK'&&e.data.requestId===requestId){removeEventListener('message',handler);resolve(e.data.payload);}};addEventListener('message',handler);iframe.contentWindow.postMessage({channel:'yaoanxin-demo',version:1,requestId,type,payload},location.origin);}),{type,payload});
  const click=a=>f.locator(`#modal-root [data-action="${a}"]:visible`).first().click();
  const nav=p=>f.locator(`[data-action="navigate"][data-page="${p}"]`).click();
  const show=async()=>{await page.locator('#open-app').click();await f.waitForFunction(()=>!document.getElementById('app').inert);};
  const clock=(time,dateOffset=1)=>request('CLOCK',{dateOffset,time});
  const noteRef=n=>({notificationId:n.id,eventId:n.eventId,profileId:n.profileId,date:n.date,recipientId:n.recipientId});
  await show();await request('RESET_REQUEST');await click('confirm-reset');if(await f.locator('#modal-root .focus-sheet').count())await click('close-modal');
  await clock('07:55');await nav('home');await clock('08:00');await f.locator('#modal-root .focus-sheet').waitFor();
  ok((await f.locator('#modal-root .focus-progress').innerText()).includes('1 / 2'),'同到点两药逐项队列1/2');const queued=(await state()).doseEvents.filter(e=>e.profileId==='profile-zhang'&&e.date==='2026-09-14'&&e.slot==='早餐');
  await click('take');ok((await f.locator('#modal-root .focus-progress').innerText()).includes('2 / 2'),'只记录第一项后显示第二项');ok((await state()).doseEvents.filter(e=>queued.some(q=>q.id===e.id)&&e.status==='taken').length===1,'一键只影响一项');
  await click('dose-confirm');ok(await f.getByRole('heading',{name:'确认本次记录',exact:true}).count()===1,'本次无需服用仍需简短确认');await click('confirm-dose');
  ok(await f.locator('#modal-root .focus-sheet').count()===0&&(await state()).doseEvents.filter(e=>queued.some(q=>q.id===e.id)&&e.status==='skipped').length===1,'第二声明完成后退出队列');await f.locator('[data-action="undo"]').click();ok((await state()).doseEvents.filter(e=>queued.some(q=>q.id===e.id)&&e.status==='skipped').length===0,'聚焦队列撤销仍有效');
  await request('OPTIONS',{simulationMode:'failure'});await clock('11:00');const failed=(await state()).notificationLogs.find(n=>n.kind==='N2'&&n.date==='2026-09-14'&&n.deliveryState==='failed');ok(failed,'失败模拟保存原通知状态');
  await request('SWITCH_ACCOUNT',{accountId:'child-li'});await page.locator('#show-desktop').click();if(await page.locator('#banner.is-visible').count())await page.locator('#banner-close').click();await request('SCENE',{kind:'N2'});ok(!(await page.locator('#banner').getAttribute('class')).includes('is-visible'),'发送失败不伪装送达横幅');
  await request('OPTIONS',{simulationMode:'online'});await request('RETRY');const retried=(await state()).notificationLogs.find(n=>n.id===failed.id);ok(retried.deliveryState==='delivered'&&retried.deliveryAttempts===2,'原ID重试只补送达元数据');const count=(await state()).notificationLogs.length;await request('RETRY');ok((await state()).notificationLogs.length===count,'再次重试不产生新通知');
  await show();await nav('home');await f.locator('[data-action="home-add-med"]').click();await f.locator('[name="name"]').fill('张阿姨独立草稿');await request('SWITCH_PROFILE',{profileId:'profile-wang'});ok(!(await f.locator('body').innerText()).includes('张阿姨独立草稿'),'切王叔叔不会泄露张阿姨草稿');await f.locator('[data-action="home-add-med"]').click();await f.locator('[name="name"]').fill('王叔叔独立草稿');await request('SWITCH_PROFILE',{profileId:'profile-zhang'});ok(await f.locator('[name="name"]').inputValue()==='张阿姨独立草稿','回张阿姨恢复其草稿');await request('SWITCH_PROFILE',{profileId:'profile-wang'});ok(await f.locator('[name="name"]').inputValue()==='王叔叔独立草稿','回王叔叔恢复其草稿');
  await request('RESET_REQUEST');const pendingNotice=(await state()).notificationLogs.find(n=>n.kind==='N2'&&n.recipientId==='child-li');await request('OPEN_NOTIFICATION',noteRef(pendingNotice));ok(await f.getByRole('button',{name:'确认恢复',exact:true}).count()===1,'晚到通知不能覆盖恢复确认');await click('confirm-reset');if(await f.locator('#modal-root .focus-sheet').count())await click('close-modal');
  // 用独立测试存档准备取消与解绑后的旧通知，打开时重新鉴权。
  const initial=await state();const oldN1=initial.notificationLogs.find(n=>n.kind==='N1');
  await f.evaluate(({id})=>{const key='silver-health-data-v1',d=JSON.parse(localStorage.getItem(key));d.doseEvents.find(e=>e.id===id).cancelledAt=MedRules.now(d);localStorage.setItem(key,JSON.stringify(d));},{id:oldN1.eventId});await page.reload();await page.waitForFunction(()=>document.getElementById('ready-status').textContent.includes('已就绪'));f=page.frames().find(f=>f.url().includes('index.html?demo=1'));await show();await request('OPEN_NOTIFICATION',noteRef(oldN1));ok((await f.getByRole('dialog').innerText()).includes('已取消')&&await f.getByRole('dialog').locator('[data-action="take"]').count()===0,'已取消任务的旧通知不恢复动作');await click('close-modal');
  const d=await state(),oldN2=d.notificationLogs.find(n=>n.kind==='N2'&&n.profileId==='profile-zhang');
  await f.evaluate(()=>{const key='silver-health-data-v1',d=JSON.parse(localStorage.getItem(key));d.accounts.find(a=>a.id==='child-li').boundProfileIds=[];localStorage.setItem(key,JSON.stringify(d));});await page.reload();await page.waitForFunction(()=>document.getElementById('ready-status').textContent.includes('已就绪'));f=page.frames().find(f=>f.url().includes('index.html?demo=1'));await show();if(await f.locator('#modal-root .focus-sheet').count())await click('close-modal');await request('SWITCH_ACCOUNT',{accountId:'child-li'});
  ok((await request('OPEN_NOTIFICATION',noteRef(oldN2))).ok===false,'已解绑后旧N2拒绝展示健康详情');ok(await page.locator('#notice-select option').count()===0,'解绑后外层不再接收通知健康摘要');
  await request('RESET_REQUEST');await click('confirm-reset');if(await f.locator('#modal-root .focus-sheet').count())await click('close-modal');await request('SWITCH_ACCOUNT',{accountId:'child-li'});await nav('home');await page.locator('#banner-close').click({timeout:1000}).catch(()=>{});
  await page.setViewportSize({width:1280,height:1000});await page.locator('#show-desktop').click();
  // WAAPI可暂停CSS transition，从中间帧检查不是终态截图冒充实际动效。
  await page.evaluate(()=>{const el=document.getElementById('app-container');el.style.transitionDuration='1000ms';});await page.locator('#launch-app').click();
  const motion=await page.locator('#app-container').evaluate(el=>{const animations=el.getAnimations();animations.forEach(a=>{a.pause();a.currentTime=120;});return{count:animations.length,transform:getComputedStyle(el).transform,opacity:getComputedStyle(el).opacity};});
  ok(motion.count>0&&motion.transform!=='none','应用展开有可检查的实际中间帧');await page.screenshot({path:`${artifactDir}/motion-midframe.png`});await page.locator('#app-container').evaluate(el=>{el.getAnimations().forEach(a=>{a.finish();});el.style.transitionDuration='';});
  await page.locator('#show-desktop').click();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${artifactDir}/ios-desktop-overview.png`,animations:'disabled'});
  await show();await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:`${artifactDir}/ios-app-overview.png`,animations:'disabled'});
  const reversal=await page.evaluate(()=>{const el=document.getElementById('app-container');el.style.transitionDuration='1000ms';document.getElementById('show-desktop').click();getComputedStyle(el).transform;el.getAnimations().forEach(a=>{a.pause();a.currentTime=100;});const before=new DOMMatrix(getComputedStyle(el).transform);document.getElementById('open-app').click();const after=new DOMMatrix(getComputedStyle(el).transform);el.getAnimations().forEach(a=>{a.finish();});el.style.transitionDuration='';return Math.max(Math.abs(before.a-after.a),Math.abs(before.d-after.d),Math.abs(before.e-after.e),Math.abs(before.f-after.f));});ok(reversal<.1,'收起中反向展开连续承接当前变换');
  await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#show-desktop').click();await show();ok(await page.locator('#app-container').evaluate(el=>getComputedStyle(el).transform)==='none','减少动态效果静态展开');await page.emulateMedia({reducedMotion:'no-preference'});
  await page.goto(`${BASE_URL}/index.html`);ok(await page.getByRole('heading',{name:'首页看板',exact:true}).count()===1,'原index入口独立可用');
  ok(errors.length===0,`脚本错误${errors.length}`);return{passed:checks.length,checks,errors};
}
