async(page,{artifactDir,theme='ios'}={})=>{
 const BASE_URL = process.env.TEST_BASE_URL || 'http://127.0.0.1:8765';
 const checks=[],errors=[],external=[],requests=[];page.on('pageerror',e=>errors.push(e.message));const ok=(v,s)=>{if(!v)throw Error(`${s}；最后通过 ${checks.at(-1)}`);checks.push(`${theme}：${s}`);};
 await page.context().route('**/*',route=>{const url=new URL(route.request().url());requests.push(url.href);if(url.origin===new URL(BASE_URL).origin)return route.continue();external.push(url.href);return route.abort();});
 await page.addInitScript(()=>{window.__permissionCalls=[];window.__outerWrites=[];if(navigator.mediaDevices)navigator.mediaDevices.getUserMedia=()=>{window.__permissionCalls.push('microphone');throw Error('禁止真实录音');};if(window.Notification)Notification.requestPermission=()=>{window.__permissionCalls.push('notification');throw Error('禁止真实通知许可');};const original=Storage.prototype.setItem;Storage.prototype.setItem=function(k,v){if(window===top&&k==='silver-health-data-v1')window.__outerWrites.push(k);return original.call(this,k,v);};});
 await page.goto(`${BASE_URL}/demo.html`);await page.waitForFunction(()=>document.querySelector('#ready-status').textContent.includes('已就绪'));let f=page.frames().find(f=>f.url().includes('index.html?demo=1'));const marker=await f.evaluate(()=>performance.timeOrigin);
 const state=()=>f.evaluate(()=>JSON.parse(localStorage.getItem('silver-health-data-v1'))),click=a=>f.locator(`#modal-root [data-action="${a}"]:visible`).first().click(),nav=p=>f.locator(`[data-action="navigate"][data-page="${p}"]`).click();
 const control=async(type,payload={})=>page.evaluate(({type,payload})=>new Promise((resolve,reject)=>{const frame=document.getElementById('app-frame'),requestId=`final-${Math.random()}`,timer=setTimeout(()=>{removeEventListener('message',handle);reject(Error('ACK timeout'));},5000);function handle(e){if(e.source===frame.contentWindow&&e.data?.type==='ACK'&&e.data.requestId===requestId){clearTimeout(timer);removeEventListener('message',handle);resolve(e.data.payload);}}addEventListener('message',handle);frame.contentWindow.postMessage({channel:'yaoanxin-demo',version:1,requestId,type,payload},location.origin);}),{type,payload});
 const setTheme=async os=>{await page.locator(`.system-picker [data-os="${os}"]`).click();await page.waitForFunction(os=>document.querySelector('#phone').dataset.os===os&&document.querySelector('#app-container').style.visibility==='visible',os);await f.waitForFunction(os=>document.documentElement.dataset.os===os,os);};
 const show=async()=>{await page.locator('#open-app').click();await f.waitForFunction(()=>!document.getElementById('app').inert);},desktop=async()=>{await page.locator('#show-desktop').click();await f.waitForFunction(()=>document.getElementById('app').inert);};
 const closeFocus=async()=>{if(await f.locator('#modal-root .focus-sheet').count()){await click('close-modal');await nav('home');}};
 const send=async text=>{await f.locator('#chat-input').fill(text);await f.locator('[data-form="chat"] button[type="submit"]').click();await f.waitForFunction(()=>!document.querySelector('.chat-status')?.textContent.includes('处理中'));};
 await show();await control('RESET_REQUEST');await click('confirm-reset');await closeFocus();await control('CLOCK',{dateOffset:0,time:'07:55'});await control('SWITCH_ACCOUNT',{accountId:'child-li'});await setTheme(theme);await nav('home');await f.locator('[data-action="home-add-med"]').click();
 await f.locator('[name="name"]').fill(`三系统测试药-${theme}`);await f.locator('[name="doseValue"]').fill('1');await f.locator('[name="doseUnit"]').fill('片');await f.locator('[name="slots"][value="早餐"]').check();await f.locator('[name="slots"][value="午餐"]').check();await f.locator('[data-action="meal"][data-slot="早餐"][data-meal="餐后"]').click();await f.locator('[data-form="medicine"] button[type="submit"]').click();
 ok(!(await state()).medicationPlans.some(p=>p.name===`三系统测试药-${theme}`),'核对前未创建计划');await click('save-med');let d=await state();const plan=d.medicationPlans.at(-1),morning=d.doseEvents.find(e=>e.planId===plan.id&&e.slot==='早餐'),lunch=d.doseEvents.find(e=>e.planId===plan.id&&e.slot==='午餐');ok(plan.createdBy==='child-li'&&plan.assisted&&morning.status==='pending'&&lunch.status==='pending','子女一条两时段计划生成两个未声明任务');
 const receiver=theme==='ios'?'harmonyos':theme==='harmonyos'?'ios':'android';await control('SWITCH_ACCOUNT',{accountId:'elder-zhang'});await setTheme(receiver);ok(await f.evaluate(()=>JSON.parse(sessionStorage.getItem('silver-health-view-v1')).accountId)==='elder-zhang','主题与身份独立，接收对象不变');await desktop();await control('CLOCK',{dateOffset:0,time:'08:00'});d=await state();const n1=d.notificationLogs.find(n=>n.kind==='N1'&&n.eventId===morning.id);ok(n1?.deliveryState==='delivered','自建计划到点生成N1');await page.locator('#notice-select').selectOption(n1.id);await page.locator('#replay-notice').click();ok((await page.locator('#banner-body').innerText()).includes(plan.name),'N1横幅包含原药名、剂量和时段');await page.screenshot({path:`${artifactDir}/${theme}-desktop-n1.png`,animations:'disabled'});
 await page.locator('#banner-open').click();await f.locator('#modal-root .focus-sheet').waitFor();const original=JSON.stringify((await state()).doseEvents.find(e=>e.id===morning.id));await click('close-modal');ok(JSON.stringify((await state()).doseEvents.find(e=>e.id===morning.id))===original,'关闭通知提醒不改事实或消耗延后');ok(await f.locator('.nav-item.is-active[data-page="home"]').count()===1&&await f.locator('#modal-root .focus-sheet').count()===0,'关闭提醒回首页且不重弹');await page.locator('#open-notice').click();await f.locator('#modal-root [data-action="view-focus-task"]').click();ok(await f.locator(`[data-task-id="${morning.id}"]`).count()>0,'仅查看对应任务进入正确日期时段列表');await f.locator(`[data-task-id="${morning.id}"] [data-action="take"]`).click();ok((await state()).doseEvents.find(e=>e.id===morning.id).status==='taken','查看任务后列表本人打卡');await f.locator('[data-action="undo"]').click();ok((await state()).doseEvents.find(e=>e.id===morning.id).status==='pending','列表五秒撤销保持原任务');
 await closeFocus();await nav('home');await f.locator('[data-action="assistant"]').click();await send('今天吃什么药');await f.locator(`[data-action="chat-task"][data-id="${morning.id}"]`).click();await send('这次药吃过了');const recorded=(await state()).doseEvents.find(e=>e.id===morning.id);ok(recorded.status==='taken'&&!recorded.actual,'A20明确目标下这次药吃过了无需实际细节');await click('close-modal');await control('SWITCH_ACCOUNT',{accountId:'child-li'});await setTheme(theme);await nav('home');ok((await f.locator('.page-content').innerText()).includes(plan.name)&&await f.locator('[data-action="take"]').count()===0,'换回子女看同一药物和声明，无代打按钮');
 await control('CLOCK',{dateOffset:0,time:'16:00'});d=await state();const n2=d.notificationLogs.find(n=>n.kind==='N2'&&n.eventId===lunch.id&&n.recipientId==='child-li'&&n.warningRound==='deadline');ok(n2,'午餐截止生成子女N2截止轮');await page.locator('#notice-select').selectOption(n2.id);await page.locator('#open-notice').click();ok(await f.locator(`[data-task-id="${lunch.id}"]`).count()>0&&await f.locator('[data-action="take"]').count()===0,'N2进入原对象历史，不进入代打');await f.locator(`[data-task-id="${lunch.id}"] [data-action="remind"]`).click();d=await state();const n3=d.notificationLogs.find(n=>n.kind==='N3'&&n.eventId===lunch.id);ok(n3?.recipientId==='elder-zhang'&&await f.locator(`[data-task-id="${lunch.id}"] [data-action="remind"]`).isDisabled(),'N3由子女授权动作产生并受冷却');
 await control('SWITCH_ACCOUNT',{accountId:'elder-zhang'});await setTheme(receiver);await desktop();await page.locator('#notice-select').selectOption(n3.id);await page.locator('#replay-notice').click();await page.locator('#banner-open').click();await f.locator('#modal-root .focus-sheet').waitFor();await f.locator('#modal-root [data-action="snooze"][data-minutes="30"]').click();await control('CLOCK',{dateOffset:0,time:'16:29'});ok(await f.evaluate(id=>{const d=JSON.parse(localStorage.getItem('silver-health-data-v1'));return MedRules.stateOf(d.doseEvents.find(e=>e.id===id),d)==='snoozed';},lunch.id),'N3延后保护跨原午餐截止仍有效');await control('CLOCK',{dateOffset:0,time:'16:30'});ok(await f.evaluate(id=>{const d=JSON.parse(localStorage.getItem('silver-health-data-v1'));return MedRules.stateOf(d.doseEvents.find(e=>e.id===id),d)==='overdue';},lunch.id),'保护结束精确恢复超时');await closeFocus();await nav('home');await f.locator('[data-action="assistant"]').click();await send('今天吃什么药');await f.locator(`[data-action="chat-task"][data-id="${lunch.id}"]`).click();await send('这次已经吃过了，只吃了半片');d=await state();const madeup=d.doseEvents.find(e=>e.id===lunch.id);ok(madeup.status==='taken'&&madeup.actual.includes('与计划不同')&&madeup.snoozeUsed===1,'逾期明确补记保留自述差异及已用延后');
 await f.locator('[data-action="chat-mode"][data-mode="voice"]').click();await f.locator('[data-chat-example]').selectOption('10');const healthCount=d.healthRecords.length;await click('voice-experience');ok((await state()).healthRecords.length===healthCount,'示例预览不保存测量');await send('身高160厘米，体重60公斤，今天16:30测量');await f.locator('#chat-input').fill('切系统仍然保留的未发送文字');const messages=await f.locator('.chat-stream').innerText(),business=JSON.stringify({p:d.medicationPlans,e:d.doseEvents,h:d.healthRecords});
 for(const os of ['ios','harmonyos','android']){await setTheme(os);ok(await f.locator('#chat-input').inputValue()==='切系统仍然保留的未发送文字'&&(await f.locator('.chat-stream').innerText())===messages,`切${os}保留消息和未发送输入`);ok(await f.evaluate(()=>performance.timeOrigin)===marker,`切${os}不重载iframe`);}
 await desktop();await show();ok(await f.locator('#chat-input').inputValue()==='切系统仍然保留的未发送文字','返回桌面再打开保持聊天草稿');const afterThemes=await state();ok(JSON.stringify({p:afterThemes.medicationPlans,e:afterThemes.doseEvents,h:afterThemes.healthRecords})===business,'主题与桌面动作不改业务历史');await click('chat-form-health');await f.locator('[name="weight"]').fill('61');await f.locator('[name="weight"]').fill('60');await f.locator('[data-form="health"] button[type="submit"]').click();await click('save-health');d=await state();const body=d.healthRecords.at(-1);ok(body.type==='body'&&body.values.height===160&&body.values.weight===60&&body.source.includes('模拟')&&body.source.includes('手动修改'),'示例加文字加手动核对后保存身体指标及混合来源');await click('close-modal');await nav('health');await f.locator('[data-action="health-tab"][data-value="body"]').click();ok((await f.locator('.page-content').innerText()).includes('23.4'),'新测量更新BMI23.4');
 ok(external.length===0&&requests.length>=5,'屏蔽全部外网后完整流程可用且无外部请求');ok((await page.evaluate(()=>window.__permissionCalls.length+window.__outerWrites.length))===0&&(await f.evaluate(()=>window.__permissionCalls.length))===0,'无真实麦克风通知许可，外层不写业务存储');await page.reload();await page.waitForFunction(()=>document.querySelector('#ready-status').textContent.includes('已就绪'));f=page.frames().find(f=>f.url().includes('index.html?demo=1'));ok((await state()).healthRecords.some(r=>r.id===body.id)&&(await state()).doseEvents.find(e=>e.id===morning.id).status==='taken','刷新恢复跨系统保存结果');
 await show();await control('RESET_REQUEST');await click('confirm-reset');await page.waitForFunction(()=>document.querySelector('#phone').dataset.os==='ios');d=await state();ok(d.dateOffset===0&&d.notificationStyle==='ios'&&d.simulationMode==='online'&&!d.medicationPlans.some(p=>p.id===plan.id)&&!d.notificationLogs.some(n=>n.eventId===lunch.id),'恢复初始数据清掉新增计划提醒日期并同步默认iOS');ok(errors.length===0,'脚本无错误');return{passed:checks.length,checks,errors,theme,externalRequests:external};
}
